#!/usr/bin/env python3
"""Map Android app files to a deterministic tree with per-file line counts."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

DEFAULT_EXTENSIONS = {
    ".kt", ".java", ".xml", ".kts", ".gradle", ".pro", ".properties",
    ".json", ".js", ".html", ".css", ".md", ".txt", ".toml", ".aidl",
}
SKIP_PARTS = {"build", ".gradle", ".idea"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--source", default="app")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/local/audits/ANDROID-FILETREE-LINE-MAP.md"),
    )
    return parser.parse_args()


def line_count(path: Path) -> int:
    with path.open("r", encoding="utf-8-sig", errors="replace", newline="") as handle:
        return sum(1 for _ in handle)


def included(path: Path) -> bool:
    if any(part in SKIP_PARTS for part in path.parts):
        return False
    if path.name in {"gradlew", "gradlew.bat"}:
        return True
    return path.suffix.lower() in DEFAULT_EXTENSIONS


def render_tree(files: list[Path], source_root: Path) -> list[str]:
    children: dict[tuple[str, ...], dict[str, set[str]]] = defaultdict(
        lambda: {"dirs": set(), "files": set()}
    )
    counts: dict[tuple[str, ...], int] = {}

    for path in files:
        relative = path.relative_to(source_root)
        parts = relative.parts
        counts[parts] = line_count(path)
        for index in range(len(parts) - 1):
            parent = parts[:index]
            children[parent]["dirs"].add(parts[index])
        children[parts[:-1]]["files"].add(parts[-1])

    output = [f"{source_root.name}/"]

    def walk(parent: tuple[str, ...], prefix: str) -> None:
        entries = [(name, True) for name in sorted(children[parent]["dirs"])]
        entries += [(name, False) for name in sorted(children[parent]["files"])]
        for index, (name, is_dir) in enumerate(entries):
            last = index == len(entries) - 1
            connector = "└─ " if last else "├─ "
            if is_dir:
                output.append(f"{prefix}{connector}{name}/")
                walk(parent + (name,), prefix + ("   " if last else "│  "))
            else:
                count = counts[parent + (name,)]
                output.append(f"{prefix}{connector}{name} [{count:,} lines]")

    walk((), "")
    return output


def category(path: Path, source_root: Path) -> str:
    relative = path.relative_to(source_root).as_posix()
    if relative.startswith("src/main/java/"):
        return "Production Kotlin/Java"
    if relative.startswith("src/test/"):
        return "JVM tests"
    if relative.startswith("src/androidTest/"):
        return "Instrumented tests"
    if relative.startswith("src/debug/"):
        return "Debug source"
    if relative.startswith("src/main/res/"):
        return "Android resources"
    if relative.startswith("src/main/assets/"):
        return "Assets"
    return "Module config/other"


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    source_root = (root / args.source).resolve()
    output_path = args.output if args.output.is_absolute() else root / args.output
    files = sorted(path for path in source_root.rglob("*") if path.is_file() and included(path))

    category_files: dict[str, list[Path]] = defaultdict(list)
    for path in files:
        category_files[category(path, source_root)].append(path)

    total_lines = sum(line_count(path) for path in files)
    lines = [
        "# Android file tree and per-file line map",
        "",
        "Generated by `python scripts/map-android-filetree.py` from the current working tree.",
        "Build outputs, IDE metadata, Gradle caches, binaries, fonts, and images are excluded.",
        "",
        "## Summary",
        "",
        f"- Files mapped: {len(files):,}",
        f"- Text lines mapped: {total_lines:,}",
    ]
    for name in (
        "Production Kotlin/Java", "JVM tests", "Instrumented tests", "Debug source",
        "Android resources", "Assets", "Module config/other",
    ):
        grouped = category_files.get(name, [])
        lines.append(f"- {name}: {len(grouped):,} files / {sum(line_count(path) for path in grouped):,} lines")

    lines += ["", "## Complete file tree", "", "```text"]
    lines += render_tree(files, source_root)
    lines += ["```", ""]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"mapped {len(files)} files / {total_lines} lines")
    print(output_path.relative_to(root).as_posix())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
